/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TicketsTicketCodeRouteImport } from './routes/tickets.$ticketCode'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostRegisterRouteImport } from './routes/host.register'
import { Route as HostSlugRouteImport } from './routes/host.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as HostsHostIdInvitesRouteImport } from './routes/hosts.$hostId.invites'
import { Route as EventsEventIdCheckInRouteImport } from './routes/events.$eventId.check-in'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsEventIdRouteImport } from './routes/dashboard.events.$eventId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketCodeRoute = TicketsTicketCodeRouteImport.update({
  id: '/$ticketCode',
  path: '/$ticketCode',
  getParentRoute: () => TicketsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRegisterRoute = HostRegisterRouteImport.update({
  id: '/host/register',
  path: '/host/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugRoute = HostSlugRouteImport.update({
  id: '/host/$slug',
  path: '/host/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdInvitesRoute = HostsHostIdInvitesRouteImport.update({
  id: '/hosts/$hostId/invites',
  path: '/hosts/$hostId/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdCheckInRoute = EventsEventIdCheckInRouteImport.update({
  id: '/events/$eventId/check-in',
  path: '/events/$eventId/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/dashboard/events/new',
  path: '/dashboard/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/dashboard/events/$eventId',
  path: '/dashboard/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/signin': typeof SigninRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/$slug': typeof HostSlugRoute
  '/host/register': typeof HostRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/tickets/$ticketCode': typeof TicketsTicketCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/hosts/$hostId/invites': typeof HostsHostIdInvitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/signin': typeof SigninRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/$slug': typeof HostSlugRoute
  '/host/register': typeof HostRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/tickets/$ticketCode': typeof TicketsTicketCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/hosts/$hostId/invites': typeof HostsHostIdInvitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/signin': typeof SigninRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/$slug': typeof HostSlugRoute
  '/host/register': typeof HostRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/tickets/$ticketCode': typeof TicketsTicketCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/hosts/$hostId/invites': typeof HostsHostIdInvitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/my-events'
    | '/signin'
    | '/tickets'
    | '/dashboard/reviews'
    | '/events/$slug'
    | '/host/$slug'
    | '/host/register'
    | '/invite/$token'
    | '/tickets/$ticketCode'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/new'
    | '/events/$eventId/check-in'
    | '/hosts/$hostId/invites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/my-events'
    | '/signin'
    | '/tickets'
    | '/dashboard/reviews'
    | '/events/$slug'
    | '/host/$slug'
    | '/host/register'
    | '/invite/$token'
    | '/tickets/$ticketCode'
    | '/dashboard'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/new'
    | '/events/$eventId/check-in'
    | '/hosts/$hostId/invites'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/my-events'
    | '/signin'
    | '/tickets'
    | '/dashboard/reviews'
    | '/events/$slug'
    | '/host/$slug'
    | '/host/register'
    | '/invite/$token'
    | '/tickets/$ticketCode'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/new'
    | '/events/$eventId/check-in'
    | '/hosts/$hostId/invites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  SigninRoute: typeof SigninRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostSlugRoute: typeof HostSlugRoute
  HostRegisterRoute: typeof HostRegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  EventsEventIdCheckInRoute: typeof EventsEventIdCheckInRoute
  HostsHostIdInvitesRoute: typeof HostsHostIdInvitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketCode': {
      id: '/tickets/$ticketCode'
      path: '/$ticketCode'
      fullPath: '/tickets/$ticketCode'
      preLoaderRoute: typeof TicketsTicketCodeRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/register': {
      id: '/host/register'
      path: '/host/register'
      fullPath: '/host/register'
      preLoaderRoute: typeof HostRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug': {
      id: '/host/$slug'
      path: '/host/$slug'
      fullPath: '/host/$slug'
      preLoaderRoute: typeof HostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/invites': {
      id: '/hosts/$hostId/invites'
      path: '/hosts/$hostId/invites'
      fullPath: '/hosts/$hostId/invites'
      preLoaderRoute: typeof HostsHostIdInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/check-in': {
      id: '/events/$eventId/check-in'
      path: '/events/$eventId/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof EventsEventIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/dashboard/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/$eventId': {
      id: '/dashboard/events/$eventId'
      path: '/dashboard/events/$eventId'
      fullPath: '/dashboard/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TicketsRouteChildren {
  TicketsTicketCodeRoute: typeof TicketsTicketCodeRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketCodeRoute: TicketsTicketCodeRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  SigninRoute: SigninRoute,
  TicketsRoute: TicketsRouteWithChildren,
  DashboardReviewsRoute: DashboardReviewsRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostSlugRoute: HostSlugRoute,
  HostRegisterRoute: HostRegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  EventsEventIdCheckInRoute: EventsEventIdCheckInRoute,
  HostsHostIdInvitesRoute: HostsHostIdInvitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
